;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="GameplayAbility.Locomotion.Run",NewTagName="Ability.Locomotion.Run")
+GameplayTagRedirects=(OldTagName="GameplayAbility.Locomotion",NewTagName="Ability.Locomotion")
+GameplayTagRedirects=(OldTagName="GameplayAbility",NewTagName="Ability")
+GameplayTagList=(Tag="Ability.Locomotion.Crouch",DevComment="")
+GameplayTagList=(Tag="Ability.Locomotion.Run",DevComment="")
+GameplayTagList=(Tag="Attachment.Identity.Sight.Standard",DevComment="")
+GameplayTagList=(Tag="Attachment.Slot.Sight",DevComment="")
+GameplayTagList=(Tag="Attachment.Type.Sight",DevComment="")
+GameplayTagList=(Tag="Character.State.Locomotion.Crouch",DevComment="")
+GameplayTagList=(Tag="Character.State.Locomotion.Run",DevComment="")
+GameplayTagList=(Tag="Item.Identity.Ammo.9mm",DevComment="")
+GameplayTagList=(Tag="Item.Identity.Weapon.Glock17",DevComment="")

